### ISSUE TITLE
New feature: Generate alert when a motor has not oiled for 2n target time

### ISSUE THREAD

**Issue by naylom** [naylom/OilerExample#4]
Generate an alert when a motor has not completed its number of outputs in twice the time between restarting the oiler

**Comment by jjuliann** [comment]
Rather than a fixed 2n (this was only an example) can we let the user choose the factor of n for the alert?  This would prevent people blaming me/us if their lathe seizes!

**Comment by naylom** [comment]
Sure, will make it a #define that can be changed by the user
